- hosts: all
  # Uncomment if installing locally
  #connection: local
  become: yes
  vars:
    ansible_user: "user"
    #uncomment and install sshpass if not using SSH keys
    #ansible_password: "ssh_password"
    ansible_become_pass: "sudo_password"
  roles:
    - role: "{{ playbook_dir }}"
      vars:
        # Surround in [] if using IPv6 address.
        # Example: [2000:1234::33]
        endpoint: "server_ip_or_hostname"
        # First usable will be taken for docker network
        private_ipv4_network: "192.168.254.0"
        private_ipv4_wireguard_address: "192.168.254.2"
        private_ipv4_netmask: "24"
        # Adding ffff to the prefix to help avoid conflict with
        # routers, etc. since the Docker network will take 
        # sipv6_prefix:ffff::1 for itself
        # Comment out enable_ipv6 for ipv4 only hosts.
        # server_ipv6_prefix, net_cidr, & wireguard_ipv6
        # will be ignored.
        # Comment out enable_ipv6 to disable IPv6
        enable_ipv6: yes
        server_ipv6_prefix: "ipv6_prefix:ffff::"
        docker_ipv6_net_cidr: "124"
        wireguard_ipv6: "ipv6_prefix:ffff::2"
        dns: "desired_client_dns"
        # Uncomment the following line to allow specified private
        # subnet(s) through tunnel if exclude_private_addresses is defined.
        # Comma separate if specifying multiple subnets.
        #allowed_private_subnets: 192.168.1.0/24, 10.10.0.0/16
        listen_port: 51820
        # Change based on what your Ubuntu install shows
        # from `ip a`
        network_dev: "ens3"
        arch: "amd64"
        users:
          - "user1"
          - "user2"
          - "user3"
          - "user4"
